import React from 'react';
import { 
  ShieldAlert, 
  Info, 
  AlertTriangle, 
  Cpu, 
  CheckCircle2, 
  Scale, 
  DollarSign, 
  AlertCircle 
} from 'lucide-react';
import { formatCurrencyINR } from '../../utils/customerHistory.js';

export default function SystemRecommendationCard({ 
  triageResult, 
  orderValue = 0,
  storedReview = null 
}) {
  if (!triageResult) return null;

  const { risk_score = 0, risk_category = 'MEDIUM', priority_label = 'Human Review', recommendation = '' } = triageResult;
  const isHighValue = orderValue >= 40000;
  const humanDecision = storedReview?.decision?.decision_type;
  const isOverridden = storedReview?.decision?.override;

  const getScoreColor = (score) => {
    if (score >= 70) return 'text-red-400';
    if (score >= 50) return 'text-amber-400';
    if (score >= 25) return 'text-yellow-400';
    return 'text-emerald-400';
  };

  const getCategoryClass = (category) => {
    switch (category) {
      case 'CRITICAL': return 'badge-risk-critical';
      case 'HIGH': return 'badge-risk-high';
      case 'MEDIUM': return 'badge-risk-medium';
      case 'LOW': return 'badge-risk-low';
      default: return 'badge-risk-medium';
    }
  };

  return (
    <div className="system-recommendation-card form-card mb-4">
      {/* Header comparison pill: System vs Human */}
      <div className="recommendation-header-row">
        <div className="flex items-center gap-2">
          <div className="card-header-icon bg-primary-light">
            <Cpu size={18} className="icon-blue" />
          </div>
          <div>
            <span className="badge-system-indicator">Automated Scoring Engine</span>
            <h3 className="card-title text-base">Module 4 System Recommendation</h3>
          </div>
        </div>

        <div className="human-vs-system-pill">
          <span className="pill-system-tag">Advisory System Output</span>
          <span className="pill-divider">&rarr;</span>
          <span className="pill-human-tag">
            {humanDecision ? `Decided: ${humanDecision.replace('_', ' ')}` : 'Awaiting Human Final Decision'}
          </span>
        </div>
      </div>

      {/* Main Score & Recommendation Metrics Grid */}
      <div className="recommendation-metrics-grid mt-3">
        {/* Score Box */}
        <div className="metric-score-box">
          <span className="metric-lbl">Risk Score</span>
          <div className="metric-score-num-wrap">
            <span className={`metric-score-num font-serif ${getScoreColor(risk_score)}`}>
              {risk_score}
            </span>
            <span className="metric-score-max text-dim">/ 100</span>
          </div>
          <span className={`risk-category-pill ${getCategoryClass(risk_category)}`}>
            {risk_category}
          </span>
        </div>

        {/* Priority & Routing Box */}
        <div className="metric-priority-box">
          <span className="metric-lbl">Triage Priority</span>
          <div className="metric-priority-title font-semibold text-primary">
            {priority_label}
          </div>
          <p className="metric-recommendation-text text-xs text-secondary mt-1">
            {recommendation}
          </p>
        </div>

        {/* Financial Exposure Box */}
        <div className="metric-exposure-box">
          <span className="metric-lbl">Financial Exposure</span>
          <div className="metric-exposure-val font-semibold">
            {formatCurrencyINR(orderValue)}
          </div>
          <span className={`exposure-status-pill ${isHighValue ? 'badge-warn-high' : 'badge-neutral'}`}>
            {isHighValue ? 'High Financial Exposure' : 'Standard Exposure'}
          </span>
        </div>
      </div>

      {/* Mandatory Decision-Support Advisory Notice */}
      <div className="decision-support-notice-banner mt-3">
        <div className="notice-icon">
          <Info size={16} className="text-primary-light" />
        </div>
        <div className="notice-content">
          <strong className="notice-title">Advisory Decision-Support Notice:</strong>
          <p className="notice-body text-xs text-secondary">
            This risk score is a deterministic decision-support recommendation generated by rules-based triage. 
            <strong> It is not a confirmed fraud finding.</strong> The final operational decision must be made by the authorized human reviewer.
          </p>
        </div>
      </div>

      {/* Fairness Principles Strip */}
      <div className="fairness-principles-strip mt-2">
        <div className="fairness-item" title="High return frequency does not automatically imply fraud">
          <Scale size={13} className="text-dim" />
          <span>High return rate &ne; Fraud</span>
        </div>
        <div className="fairness-item" title="Past verified fraud does not invalidate genuine current damage">
          <Scale size={13} className="text-dim" />
          <span>Previous fraud history &ne; Current fraud</span>
        </div>
        <div className="fairness-item" title="Unclear photo angle does not mean the item is not damaged">
          <Scale size={13} className="text-dim" />
          <span>Low photo quality &ne; Fraud</span>
        </div>
        <div className="fairness-item" title="Expensive furniture requires careful handling, not suspicion">
          <Scale size={13} className="text-dim" />
          <span>High product value &ne; Fraud</span>
        </div>
      </div>

      {/* Override Warning if Already Overridden */}
      {isOverridden && (
        <div className="override-notification-card mt-3">
          <div className="override-badge-row">
            <AlertTriangle size={15} className="text-amber-400" />
            <span className="font-bold text-amber-300 text-xs uppercase tracking-wide">
              Manual Human Override Active
            </span>
          </div>
          <p className="text-xs text-secondary mt-1">
            <strong>Original System Triage:</strong> {risk_category} / {priority_label} &bull; 
            <strong> Human Decision:</strong> {storedReview.decision?.decision_type?.replace('_', ' ')}
          </p>
          {storedReview.decision?.override_reason && (
            <p className="override-reason-quote text-xs text-dim italic mt-1">
              &ldquo;{storedReview.decision.override_reason}&rdquo;
            </p>
          )}
        </div>
      )}
    </div>
  );
}
